version: "3"

services:
# V dev container
  vlang:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081         
    # Bind the entire parent directory to /v in container
    volumes:
      - type: bind
        source: ..
        target: /v
    tty: true
    env_file: ".env"
    
# The database
  postgres:
    image: postgres
    restart: always
    expose:               # Only expose to other containers in the network
      - 5432
    env_file: ".env"
